### ISSUE TITLE
Supporting the msvc compiler

### ISSUE THREAD

**Issue by Thysinner** [verygoodgraphics/vgg_runtime#4]
The QuickJS library is not adpated to the msvc compiler yet. We found the following projects and PRs could be references to solve the issue
- https://github.com/P-i-N/quickjs-msvc/commit/6153efadaf70ed0d388d9868e55e6bf800fc7aec
- https://github.com/pattin/winqjs
- https://github.com/anydream/quickjs-msvc

**Comment by harry75369** [comment]
We could take it already solved as msvc compiler is supported in this PR: https://github.com/verygoodgraphics/vgg_contrib/pull/5
